name: "Step 1, Sync generate.yml from Base Builder"
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/data/*'
      - 'conf/*'
      - '.github/workflows/syncbase.yml'

    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.VM_TOKEN }}

      - name: Using main branch
        run: |
          git switch main || (git fetch --all && git checkout -b main origin/main)
          git clone https://github.com/vmactions/base-builder.git

      - name: Sync generate.yml
        uses: vmactions/render@v0.0.1
        with:
          datafile: .github/data/datafile.ini
          files: |
            base-builder/.github/tpl/generate.tpl.yml : .github/workflows/generate.yml

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Sync from base-builder"
          pull: '--rebase --autostash '
          add: |
            .github/workflows/generate.yml


